server:
  port: 8080
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: dousheng
  username: root
  password: root
  charset: utf8mb4
video:
  videoPath: http://192.168.17.1:8080/public/
  coverPath: /
  maxNum: 10