server:
  port: 8080
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: db
  username: root
  password: root
  charset: utf8mb4
video:
  videoPath: http://10.21.43.245:8080/static/
  coverPath: https://
  maxNum: 10